### ISSUE TITLE
Lesson 32 this.$http is undefined

### ISSUE THREAD

**Issue by Nitzahon** [iamshaunjp/vuejs-playlist#27]
so I got an error when clicking the button:
![image](https://user-images.githubusercontent.com/8536290/138688341-b2137361-ca25-4902-aa23-d53dcbfde58a.png)

even after I copied your code 100%, still I get the error, I've installed vue-resource and used Vue.use

when I try to console.log(this.$http)  I get undefined

**Comment by Nitzahon** [comment]
It was entirely my fault, I had edited the main.js file of a different project instead without noticing

**Comment by jaerbi** [comment]
😀 good jon

пн, 25 жовт. 2021 о 14:49 Nadav Gur-Arieh ***@***.***> пише:
