### ISSUE TITLE
search bar 

### ISSUE THREAD

**Issue by itman0101** [iamshaunjp/vuejs-playlist#3]
in the videos that you put in youtube there was nothing about that search box in top of the page.
and thats not working!

**Comment by Robbt** [comment]
I believe this was covered in Lesson 35 & 36 - [link to lesson](https://www.youtube.com/watch?v=G34_yNV8FMY&index=36&list=PL4cUxeGkcC9gQcYgjhBoeQH7wiAyZNrYa) and it appears in the code branch for [Lesson 36](https://github.com/iamshaunjp/vuejs-playlist/tree/lesson-36)
